/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as OchranaOsobnychUdajovRouteImport } from './routes/ochrana-osobnych-udajov'
import { Route as PsiaSkolkaPreSteniatkaRouteImport } from './routes/psia-skolka-pre-steniatka'
import { Route as UdajePrevadzkovatelaRouteImport } from './routes/udaje-prevadzkovatela'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnychUdajovRoute = OchranaOsobnychUdajovRouteImport.update({
  id: '/ochrana-osobnych-udajov',
  path: '/ochrana-osobnych-udajov',
  getParentRoute: () => rootRouteImport,
} as any)
const PsiaSkolkaPreSteniatkaRoute = PsiaSkolkaPreSteniatkaRouteImport.update({
  id: '/psia-skolka-pre-steniatka',
  path: '/psia-skolka-pre-steniatka',
  getParentRoute: () => rootRouteImport,
} as any)
const UdajePrevadzkovatelaRoute = UdajePrevadzkovatelaRouteImport.update({
  id: '/udaje-prevadzkovatela',
  path: '/udaje-prevadzkovatela',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/psia-skolka-pre-steniatka': typeof PsiaSkolkaPreSteniatkaRoute
  '/udaje-prevadzkovatela': typeof UdajePrevadzkovatelaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/psia-skolka-pre-steniatka': typeof PsiaSkolkaPreSteniatkaRoute
  '/udaje-prevadzkovatela': typeof UdajePrevadzkovatelaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/psia-skolka-pre-steniatka': typeof PsiaSkolkaPreSteniatkaRoute
  '/udaje-prevadzkovatela': typeof UdajePrevadzkovatelaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cookies' | '/ochrana-osobnych-udajov' | '/psia-skolka-pre-steniatka' | '/udaje-prevadzkovatela'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookies' | '/ochrana-osobnych-udajov' | '/psia-skolka-pre-steniatka' | '/udaje-prevadzkovatela'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/ochrana-osobnych-udajov'
    | '/psia-skolka-pre-steniatka'
    | '/udaje-prevadzkovatela'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  OchranaOsobnychUdajovRoute: typeof OchranaOsobnychUdajovRoute
  PsiaSkolkaPreSteniatkaRoute: typeof PsiaSkolkaPreSteniatkaRoute
  UdajePrevadzkovatelaRoute: typeof UdajePrevadzkovatelaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnych-udajov': {
      id: '/ochrana-osobnych-udajov'
      path: '/ochrana-osobnych-udajov'
      fullPath: '/ochrana-osobnych-udajov'
      preLoaderRoute: typeof OchranaOsobnychUdajovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psia-skolka-pre-steniatka': {
      id: '/psia-skolka-pre-steniatka'
      path: '/psia-skolka-pre-steniatka'
      fullPath: '/psia-skolka-pre-steniatka'
      preLoaderRoute: typeof PsiaSkolkaPreSteniatkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udaje-prevadzkovatela': {
      id: '/udaje-prevadzkovatela'
      path: '/udaje-prevadzkovatela'
      fullPath: '/udaje-prevadzkovatela'
      preLoaderRoute: typeof UdajePrevadzkovatelaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  OchranaOsobnychUdajovRoute: OchranaOsobnychUdajovRoute,
  PsiaSkolkaPreSteniatkaRoute: PsiaSkolkaPreSteniatkaRoute,
  UdajePrevadzkovatelaRoute: UdajePrevadzkovatelaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
